### PR TITLE
Adding props to forked processes.

### PR DESCRIPTION
**Pull request by vjovanov**
I think this is the cleaner solution than the one [here](https://github.com/sbt-coursera/scala-grading/pull/5). WDYT?
Review by @sjrd @VladUreche

### CODE REVIEW

**Comment by VladUreche** [comment]
Yes, definitely better. But doesn't this just cover `scalaTest`?

**Comment by vjovanov** [comment]
It covers `run` and `test` according to [foking](http://www.scala-sbt.org/0.13.5/docs/Detailed-Topics/Forking.html). What else should it cover?

**Comment by VladUreche** [comment]
`testOnly`, but it should be the same as `test`. LGTM then.

**Comment by sjrd** [comment]
LGTM as well.

**Comment by vjovanov** [comment]
Let me know if I should release.

**Comment by VladUreche** [comment]
Yes, please do. Ping @heathermiller: once @vjovanov releases, you can drop my temporary hacks in the `build.sbt` file.

**Comment by vjovanov** [comment]
Make sure to move the assignment to 0.4 then. I will release soon.

**Comment by heathermiller** [comment]
Got it. Thanks guys!

**Comment by vjovanov** [comment]
Released 0.4. Please wait for 1-2 hours until it is synced and you can migrate progpar to it.

**Pull request merged**
